
matrix:
  include:
    - os: linux
      dist: trusty
      # don't actually need sudo, but I *do* want to test with bazel sandboxing
      sudo: required
      language: java
      addons:
        apt:
          packages:
            - pkg-config
            - zip
            - g++
            - zlib1g-dev
            - unzip
      before_script:
        - wget "https://github.com/bazelbuild/bazel/releases/download/0.3.2/bazel-0.3.2-installer-linux-x86_64.sh"
        - chmod +x "bazel-0.3.2-installer-linux-x86_64.sh"
        - ./bazel-0.3.2-installer-linux-x86_64.sh --user
    - os: osx
      osx_image: xcode7.3
      before_script:
        - wget "https://github.com/bazelbuild/bazel/releases/download/0.3.2/bazel-0.3.2-installer-darwin-x86_64.sh"
        - chmod +x "bazel-0.3.2-installer-darwin-x86_64.sh"
        - ./bazel-0.3.2-installer-darwin-x86_64.sh --user

cache:
  directories:
    - $HOME/.bazel/outbase

script:
  - bazel --batch --output_base=${HOME}/.bazel/outbase test //...
